# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200526_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 3, 17, 39, 6, 839573), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 3, 17, 39, 6, 840572), verbose_name='Дата'),
        ),
    ]
