# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200603_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии к статьям блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 3, 19, 20, 39, 300151), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 6, 3, 19, 20, 39, 302150), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
    ]
